papers/urls.py
from django.conf.urls import patterns, url

from papers import views

urlpatterns = patterns('',
    url(r'^new/$', views.new_listing, name='new_listing'),
    url(r'^request/(?P<id>\w+)/$', views.trade, name='trade'),
    url(r'^new-request/(?P<listing_id>\w+)/$', views.new_trade, name='new_trade'),
    url(r'^(?P<id>\w+)/$', views.listing, name='listing'),
)

tradepaper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from django.contrib import admin
from general import views
from users import views
admin.autodiscover()

urlpatterns = patterns('',
    # pass requests on to other url configs
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^papers/', include('papers.urls', namespace='papers')),
    url(r'^admin/', include(admin.site.urls)),

    # general views
    url(r'^/?$', 'general.views.home', name='home'),
    url(r'^about/?$', 'general.views.about', name='about'),
    url(r'^faq/?$', 'general.views.faq', name='faq'),
    url(r'^shipping/?$', 'general.views.shipping', name='shipping'),
    url(r'^resetpassword/?$', 'general.views.reset_password', name='reset_password'),
    url(r'^resetlink/?$', 'general.views.reset_link', name='reset_link'),

    # users views
    url(r'^login/?$', 'users.views.login', name='login'),
    url(r'^logout/?$', 'users.views.logout', name='logout'),
    url(r'^register/?$', 'users.views.register', name='register'),
    url(r'^myaccount/?$', 'users.views.my_account', name='my_account'),
    url(r'^myaccount/preferences/?$', 'users.views.preferences', name='preferences'),
    url(r'^requests/?$', 'users.views.trades', name='trades'),
    url(r'^manage/?$', 'users.views.manage', name='manage'),
    url(r'^editprofile/?$', 'users.views.edit_profile', name='edit_profile'),

    # papers views
    url(r'^browse/?$', 'papers.views.browse', name='browse'),
)

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

users/urls.py
from django.conf.urls import patterns, url

from users import views
from papers import views as papers_views

urlpatterns = patterns('',
    url(r'^(?P<name>[\w\ ]+)$', views.profile, name='profile'),
)

papers/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from shortuuidfield import ShortUUIDField

class Listing(models.Model):
    id = ShortUUIDField(primary_key=True, unique=True)
    title = models.CharField(max_length=140)
    issue = models.CharField(max_length=60)
    condition = models.IntegerField(validators = [MinValueValidator(0), MaxValueValidator(10)])
    user = models.ForeignKey('users.User')
    date_posted = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return "%s, %s" % (self.title, self.issue)

class Trade(models.Model):
    id = ShortUUIDField(primary_key=True, unique=True)
    date_initiated = models.DateTimeField(auto_now_add=True)
    listing = models.ForeignKey(Listing)
    trader = models.ForeignKey('users.User', related_name='trades_sent')
    tradee = models.ForeignKey('users.User', related_name='trades_received')

    def __str__(self):
        return "listing: %s, trader: %s" % (self.listing, self.trader)

class Message(models.Model):
    id = ShortUUIDField(primary_key=True, unique=True)
    sent_by_trader = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=4096)
    trade = models.ForeignKey(Trade, related_name='messages', null=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        if self.sent_by_trader:
            return "%s: %s" % (self.trade.trader.name, self.text)
        else:
            return "%s: %s" % (self.trade.tradee.name, self.text)

templates/tradepaper/about.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>About - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}

	<!--About-->
	<div class="about">
		<h2>About trade-paper</h2>
		<img src="http://trade-paper.com/assets/img/t-p-logo.png" />
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. <a href="/browse">So take a look around.</a></p>
		<h2>Frequently Asked Questions</font></h2>
		<p>Head over to the <a href="/faq">FAQ page.</a></p>
		<h2>Contact trade-paper</h2>
		<p>If you have any questions, requests, or any other thing you'd like to ask or tell us directly, shoot us an email at <br/><a href="mailto:info@trade-paper.com">info @ trade-paper.com</a></p>
	</div>
	<!--END About-->
	<div class="bottom"></div>
</body>

</html>

templates/tradepaper/addremove.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Add / Remove Magazines - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}

<!--My Account Content-->
<div class="mymags">
	<h2>Add/Remove My Magazines</h2>
	<div class="addmag" id="draggable"><a id="jq">+ Add a magazine</a></div>

	<!--Add Magazine dialogue:-->
	<div id="adding">
		<div class="newlisting">
			<h1>Add New Paper</h1>

			<!-- Start Error Message -->
	    {% if messages %}
	        {% for message in messages %}
	        <h2{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h2>
	        {% endfor %}
	    {% endif %}
	    <!-- End Error Message -->

			<form action="{% url 'papers:new_listing' %}" method="post" enctype="multipart/form-data">
	      {% csrf_token %}

	      <h2>Publication Title:</h2>
	      <input type="text" name="title" placeholder="title" id="new_listing_title" data-required="required" class="textfield_effect2">
	      <!--^ Make backend capitalize this properly ^-->

	      <h2>Paper Issue:</h2>
	      <input type="text" name="issue" placeholder="issue" id="new_listing_issue" data-required="required" class="textfield_effect2">

	      <h2>Condition:</h2>
	      <input type="text" name="condition" placeholder="condition out of 10" id="new_listing_condition" data-required="required" class="textfield_effect2">

	      <!--Add category picker here-->
	      <h2>Upload Images:</h2>
		  <input type="file" name="image" class="addmagup">
	  	  <input type="submit" value="Submit" class="textfield_effect trans" id="mailchimpbutton">
	    </form>

    </div><!--End #newlisting dropdown-->
	</div><!--End "#adding"-->

	<div class="mags">
		<h3>Magazines currently listed:</h3><br/>
		{% for listing in listings %}
    	<div class="browse_element"u>
      	<a class="remove" href="#">
					Remove
				</a>
				<img src="{{ listing.image.url }}" />
				<div class="browse_paper_title">
					{{ listing.title }}
				</div>
				<p>Publication Edition</p>
			</div>
		{% endfor %}
	</div><!--End ".mags"-->
</div> <!--End ".mymags"-->


<div class="bottom"></div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<script>
	$(function() {
    	$( "#draggable" ).draggable();
    	});
</script>
<script>
	$(document).ready(function() {
		$(".addmag").on("click", function() {
			$("#adding").slideToggle(400);
			$(".mags").slideToggle(400);
		});
		$("#newlisting_submit").on("click", function() {
			$("#adding").slideToggle(400);
			$(".mags").slideToggle(400);
		});
		$(".remove").on("click", function() {
			$(this).closest(".browse_element").hide(100);
			return false;
		});
	});
</script>
</body>
</html>

templates/tradepaper/faq.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>FAQ - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}

	<div class="faq">
		<h2>Frequently Asked Questions</h2>
	    <h3>What's this all about?</h3>
	    <p>If you were wondering how to possibly get in touch with us for any reason whatsoever filler filler you can do that all the way <a href="">over here.</a></p>
	    <h3>Second question would be here yeah?</h3>
	    <p>If you were wondering how to possibly get in touch with us for any reason whatsoever filler filler you can do that all the way <a href="">over here.</a></p>
	</div>

	<div class="bottom"></div>
</body>
</html>

templates/tradepaper/header.html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
{% load staticfiles %}
<link href="{% static 'tradepaper/styles.css' %}" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>

templates/tradepaper/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Home - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}
	<div class="home">
		<img src="http://trade-paper.com/assets/img/t-p-logo.png" width=250px/><br/>
		<h3><blue>trade-paper</blue> is coming soon!</h3>
		<p><blue>trade-paper</blue> is a service created to connect you, a magazine owner, to other magazine owners, letting you trade your shelved magazines for other publications that you're after.</p>
		<h3>How does it work?</h3>
		<p>Add your magazines to your profile, search for a magazine you want, and send a trade request to the user with that magazine. Once both parties agree to a trade, we'll generate your shipping label and walk you through the shipping process to make sure everyone's happy.</p>
		<h3>When does it launch?</h3>
		<p>Everything should be up and ready around <blueh>the end of September</blueh>.<br/> Sign up to get updates on our launch here:
		<!-- Begin MailChimp Signup Form -->
			<style type="text/css">
				#mc_embed_signup{ background:#fff; width:350px; margin: 0 auto;}
				/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
				   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
			</style>
			<div id="mc_embed_signup" style="width:500px;">
				<form action="//trade-paper.us8.list-manage.com/subscribe/post?u=4fd53c1fa23b2b07b47f44910&amp;id=ffb777b130" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				<label for="mce-EMAIL"></label>
				<input type="email" placeholder="email address" name="EMAIL" class="mailchimp" id="">
				<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
			    <div style="position: absolute; left: -5000px;"><input type="text" name="b_4fd53c1fa23b2b07b47f44910_ffb777b130" tabindex="-1" value=""></div>
			    <input type="submit" value="Submit" name="subscribe" class="button_effect" id="mailchimpbutton">
			  </form>

			</div>
			<script type='text/javascript' src='https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
		<!-- End MailChimp Signup Form -->
		<!-- Signup Confirmation-->
		<div id="mailchimp_confirmed"></div>

		</p>
	</div>
	<div class="bottom"></div>
</body>

</html>

templates/tradepaper/myaccount.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>My Account - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}
<!--My Account Content-->
	<div class="myaccount">
		<h2>My Account</h2>
		<div id="mabuttons">
                  <a href="{% url 'trades' %}"><mabutton>View Trade Requests</mabutton></a><!--Link to trade-request page-->
                  <a href="{% url 'manage' %}"><mabutton>Add/Remove My Magazines</mabutton></a>
			<a href="{% url 'users:profile' name=user.name %}"><mabutton>View My Profile</mabutton></a><!--Have this link to the logged-in user's profile-->
                        <a href="{% url 'edit_profile' %}"><mabutton>Edit Profile Details</mabutton></a>
                        <a href="{% url 'preferences' %}"><mabutton>Preferences</mabutton></a>
			<a href=""><mabutton>Other Link</mabutton></a>
		</div>
	</div>
	<!--End My Account Content-->
	
	<div class="bottom"></div>
</body>
</html>

templates/tradepaper/nav-bar.html
<!-- Start Framelinks -->

<div class="top"></div>
<div class="framelink" id="link1">
    <a href="{% url 'browse' %}">Browse</a>
</div>
<div class="framelink" id="link2">
    <a href="{% url 'home' %}">trade–paper</a>
</div>
<div class="framelink" id="link3">
    <form action="#" method="POST">
        <input type="text" name="query" class="search_effect" placeholder="Search">
    </form>
</div>
<div class="framelink" id="link4"><a href="{% url 'about' %}">About</a>
</div>
<div class="framelink" id="link5">
    <!--If signed in:-->
    {% if user.is_authenticated %}
    <p {% if user.unread_count %}class="uparr badge1" data-badge="{{user.unread_count}}"{% endif %}>Account</p>
        <ul>
            <li><a href="{% url 'my_account' %}">My Account</a></li>
            <li><a href="{% url 'papers:new_listing' %}">New Listing</a></li>
            <li><a href="{% url 'trades' %}" {% if user.unread_count %}id="red"{% endif %}>Requests</a></li>
            <!--<li><a href="{% url 'users:profile' name=user.name %}">My Profile</a></li>-->
            <li><a href="{% url 'logout' %}">Log Out</a></li>
        </ul>
    <!--If not signed in:-->
    {% else %}
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}
</div>

<!-- End Framelinks -->

templates/tradepaper/new-listing.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>Add New Paper - trade–paper</title>
  {% include "tradepaper/header.html" %}
</head>

<body>
  {% include "tradepaper/nav-bar.html" %}
  <div class="newlisting">
    <h1>Add New Paper</h1>
    <!-- Start Error Message -->
    {% if messages %}
        {% for message in messages %}
        <h2{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h2>
        {% endfor %}
    {% endif %}
    <!-- End Error Message -->

    <form action="{% url 'papers:new_listing' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <h2>Publication Title:</h2>
      <input type="text" name="title" placeholder="title" id="new_listing_title" data-required="required" class="textfield_effect2">
      <!--^ Make backend capitalize this properly ^-->

      <h2>Issue number:</h2>
      <input type="text" name="issue" placeholder="issue" id="new_listing_issue" data-required="required" class="textfield_effect2">

      <h2>Condition:</h2>
      <input type="text" name="condition" placeholder="condition out of 10" id="new_listing_condition" data-required="required" class="textfield_effect2">

      <!--Add category picker here-->
      <h2>Upload Images:</h2>
      <input type="file" name="image" id="new_listing_image" class="">
  	  <input type="submit" value="Submit" class="textfield_effect trans" id="mailchimpbutton">
</body>

</html>

templates/tradepaper/pending-requests.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>Pending Requests - trade–paper</title>
  {% include "tradepaper/header.html" %}
</head>

<body>
  {% include "tradepaper/nav-bar.html" %}
  <div class="pendingrequests">
    <h2>Pending Requests</h2>

    <div class="receivedrequests">
      <h3><span>Received Requests</span></h3>
      {% if received_trades %}
        {% for trade in received_trades %}
        <div id="some">
          <div class="outer">
            <div id="date">{{trade.date_initiated|date:"F j, Y"}}</div>

            <div class="middle trans">
              <a href="{% url 'papers:trade' trade.id %}">Pending trade request for {{trade.listing.title}}</a>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div id="none">
          <p>You have no pending requests.</p>
        </div>
      {% endif %}
    </div>

    <div class="sentrequests">
      <h3><span>Sent Requests<span></h3>
      {% if sent_trades %}
        {% for trade in sent_trades %}
        <div id="some">
          <div class="outer">
            <div id="date">{{trade.date_initiated|date:"F j, Y"}}</div>

            <div class="middle trans">
              <a href="{% url 'papers:trade' trade.id %}">Pending trade request for {{trade.listing.title}}</a>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div id="none">
          <p>You have no pending requests.</p>
        </div>
      {% endif %}
    </div>
  <!--Show .mailstatus class only if trade has been accepted
  <div class="mailstatus"></div>-->
  </div>

  <div class="bottom"></div>
</body>

</html>

templates/tradepaper/preferences.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Preferences - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}

	<div class="faq">
		<h2>Frequently Asked Questions</h2>
	    <h3>What's this all about?</h3>
	    <p>If you were wondering how to possibly get in touch with us for any reason whatsoever filler filler you can do that all the way <a href="">over here.</a></p>
	    <h3>Second question would be here yeah?</h3>
	    <p>If you were wondering how to possibly get in touch with us for any reason whatsoever filler filler you can do that all the way <a href="">over here.</a></p>
	</div>

	<div class="bottom"></div>
</body>
</html>

templates/tradepaper/profile.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Profile - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}
	<!--Set Page Title to "username - trade-paper"-->
	<!--Profile Header-->
	<div class="profile_head">
		<h2>Profile</h2>
		<!-- Get avatar-->
	  <img src="https://pbs.twimg.com/profile_images/433092997828202496/Lj3L-jIF_bigger.jpeg" />
		<!--Get username -->
		<div id="unamedisp">{{ user.name }}</div>
		<!--Get city location-->
		{% if user.city %}
			<h3>{{ user.city }}</h3>
		{% endif %}
		<!--Get website if any-->
		{% if user.website %}
			<h3><a href="{{ user.website }}">{{ user.website }}</a></h3>
		{% endif %}
	</div>
	<!--END Profile Header-->

	<!--Profile Content-->
	<div class="profile">
    <!-- Maybe add Profile Sorting here-->

		{% for listing in user.listing_set.all %}
    	<div class="browse_element">
        	<a href="{% url 'papers:listing' listing.id %}">
				<img src="{{ listing.image.url }}" />
			</a>
			<div class="browse_paper_title">
				<a href="{% url 'papers:listing' listing.id %}">{{ listing.title }}</a>
			</div>
			<p>Publication Issue</p>
		</div>
		{% endfor %}
	</div>
	<!--End Profile Content-->

	<div class="bottom"></div>
</body>

</html>

templates/tradepaper/resetpassword.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Password Reset - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}
	<div class="resetpassword">
		<h1>Password Reset</h1>
		<h3>Forgot your password? No worries, enter your email address below and we'll send you a link to reset your password.</h3>

		<!-- Start Error Message ("There's no account associated with that email address!") -->
		{% if messages %}
			{% for message in messages %}
			<h2{% if message.tags %} class="{{ message.tags }} errors"{% endif %}>{{ message }}</h2>
			{% endfor %}
		{% endif %}
		<!-- End Error Message -->

		<form action="{% url 'register' %}" method="post">
			{% csrf_token %}
			<h2>Email address:</h2>
			<input type="email" name="email" placeholder="email address" id="register_email" data-required="required" class="textfield_effect" autofocus>
			<input type="submit" value="Reset" class="button_effect trans" id="signup_submit">
		</form>
	</div>
	<div class="bottom"></div>
</body>
</html>

templates/tradepaper/resetpasswordhere.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Password Reset - trade–paper</title>
	{% include "tradepaper/header.html" %}
</head>

<body>
	{% include "tradepaper/nav-bar.html" %}
	<div class="resetpassword">
		<h1>Password Reset</h1>
		<h3>Neat, it's really you! Please choose a new password and enter it below.</h3>

		<!-- Start Error Message ("There's no account associated with that email address!") -->
		{% if messages %}
			{% for message in messages %}
			<h2{% if message.tags %} class="{{ message.tags }} errors"{% endif %}>{{ message }}</h2>
			{% endfor %}
		{% endif %}
		<!-- End Error Message -->

		<form action="{% url 'register' %}" method="post">
			{% csrf_token %}
			<h2>New password:</h2>
			<input type="email" name="email" placeholder="email address" id="register_email" data-required="required" class="textfield_effect" autofocus>
			<h2>Re-enter Your New Password:</h2>
			<input type="email" name="email" placeholder="email address" id="register_email" data-required="required" class="textfield_effect" autofocus>
			<input type="submit" value="Submit" class="button_effect trans" id="signup_submit">
		</form>
	</div>
	<div class="bottom"></div>
</body>
</html>

templates/tradepaper/trade-request.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>Trade Request – trade–paper</title>
  {% include "tradepaper/header.html" %}
</head>

<body>

{% include "tradepaper/nav-bar.html" %}

<!--Sign Up-->
<div class="request">

  <h1>Trade Request</h1>

  <!--Fill in blank with message receipient-->
  {% if user == trade.trader %}
  <h3>Trade Request to <FONT color="#0147FA">{{ trade.tradee.name }}</FONT><br/> for <FONT color="red">{{ listing.title }}, {{ listing.issue }}</FONT></h3>
  {% elif user == trade.tradee %}
  <h3>Trade Request from <FONT color="#0147FA">{{ trade.trader.name }}</FONT><br/> for <FONT color="red">{{ listing.title }}, {{ listing.issue }}</FONT></h3>
  {% endif %}

  {% for message in trade.messages.all %}
    {% if message.sent_by_trader == user_is_trader %}
      <div class="req_message_out">
        {{ message.text|linebreaksbr }}
      </div>
    {% else %}
      <div class="req_message_in">
        {{ message.text|linebreaksbr }}
      </div>
    {% endif %}
  {% endfor %}

  {% if trade.messages.all|length > 0 %}
  <form action="{% url 'papers:trade' trade.id %}" method="POST">
  {% else %}
  <form action="{% url 'papers:new_trade' listing.id %}" method="POST">
  {% endif %}
    {% csrf_token %}
    <textarea class="req_message_out_ta" cols="20" name="message" rows="1"></textarea>

    <div id="submitmessage">
      <input type="submit" value="Send" class="button_effect trans" id="send_message" name="send_message"/>
    </div>

    {% if user == trade.trader %}
      <div id="cancel_trade_container">
        <input type="submit" value="Cancel Trade" class="button_effect trans" id="cancel_trade" name="cancel"/>
      </div>

    {% elif user == trade.tradee %}
      <div id="confirm_trade_container">
        <input type="submit" value="Confirm Trade" class="button_effect trans" id="confirm_trade" name="confirm"/>
      </div>

      <div id="reject_trade_container">
        <input type="submit" value="Reject Trade" class="button_effect trans" id="reject_trade" name="reject"/>
      </div>
    {% endif %}
  </form>

</div>

<!--END Sign Up-->

<div class="bottom"></div>
</body>
</html>